on: [push]

jobs:
  check-db-modified:
    runs-on: ubuntu-latest
    name: Test if database modified

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: database/** # if slides or index or indexer changed 

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.check-db-modified.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
          
  index-slides:
    name: Slide Indexer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make the indexer executable
        run: chmod +x indexer.sh
        
      - name: Run indexer script
        run: ./indexer.sh