on: [push]

jobs:
  check_database_updated:
    runs-on: ubuntu-latest 
    name: Check For Database Updates
    # Expose step outputs as job outputs
    outputs:
      all_changed_and_modified_files_count: ${{ steps.changed-files.outputs.all_changed_and_modified_files_count }}

    steps:
      - name: Check out the repository to the runner
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find all changed and modified files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: database/**
      - name: List all changed and modified files
        env:
          ALL_CHANGED_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files}}
        run: |
          echo ${ALL_CHANGED_MODIFIED_FILES}
          
  index_database_slides:
    runs-on: ubuntu-latest
    name: Index Database Slides
    needs: [check_database_updated]
    if: needs.check_database_updated.outputs.all_changed_and_modified_files_count > 0
    defaults:
      run:
        working-directory: ./database
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make the indexer executable
        run: chmod +x indexer.sh
        
      - name: Run indexer script
        run: ./indexer.sh
      
      - id: commit_files
        name: Commit files  
        run:
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          if ! git diff --exit-code; then
              git add your/files/here
              git commit -am "GH Action Files added $(date)"
              git push -f origin main
          fi