on: [push]

jobs:
  check_database_updated:
    runs-on: ubuntu-latest 
    name: Test if database was updated in any form
    outputs:
      all_changed_and_modified_files_count: ${{ steps.changed-files.outputs.all_changed_and_modified_files_count }}
      all_changed_and_modified_files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
      index_exists: ${{steps.check_index_exists.outputs.files_exists}}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed and modified files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: database/**
      
      - name: List all modified files
        env:
          ALL_CHANGED_MODIFIED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_and_modified_files_count }}
          ALL_CHANGED_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
        run: |
          for file in ${ALL_CHANGED_MODIFIED_FILES}; do
            echo "$file was changed or modified"
          done     

      - name: Check index existence
        id: check_index_exists
        uses: andstor/file-existence-action@v3
        with:
          files: 'database/index.json'

      - name: Log index existence
        env:
          INDEX_EXISTS: ${{ steps.check_index_exists.outputs.files_exists }}
        run: echo "Index Exists? $INDEX_EXISTS"
    
  index_slides:
    name: Slides Indexer
    needs: [check_database_updated]
    outputs:
      new_sha: ${{ steps.sha.outputs.SHA }}

    if: needs.check_database_updated.outputs.all_changed_and_modified_files_count > 0

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
        
      - name: Run indexer script
        run: python scripts/__indexer.py
      
      - name: Push Index Changes
        run: |
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

          git add .

          if [[ -n "$(git diff --name-only --diff-filter=AM --staged)" ]];
          then
            git add .
            git commit -am "Slides Indexer [GITHUB ACTION]"
            git push  -f origin main
          fi

      - name: get sha
        id: sha
        run: |
            sha_new=$(git rev-parse HEAD)
            echo $sha_new
            echo "::set-output name=SHA::$sha_new"
    
  s3_database_sync:
    name: Sync Database To S3
    needs: [check_database_updated,index_slides]

    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'

      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.index_slides.outputs.new_sha }}
          fetch-depth: 0
      
      - name: Listing contents after checkout
        run: |
          pwd
          ls

      - name: Complete Sync with S3
        if: needs.check_database_updated.outputs.index_exists == 'false'
        run: aws s3 sync database/ s3://${{ secrets.AWS_S3_BUCKET}} --follow-symlinks --exclude "scripts/*" --delete


      - name: Diff Sync with S3s
        if: needs.check_database_updated.outputs.index_exists == 'true'
        env:
          ALL_CHANGED_MODIFIED_FILES: ${{ needs.check_database_updated.outputs.all_changed_and_modified_files}}
        run: |
          IFS=' ' read -r -a files_array <<< "$ALL_CHANGED_MODIFIED_FILES"
          CMDS=()
          for file in "${files_array[@]}"; do
            if [[ $file == database/* ]]; then
              modifiedPath="${file#database/}"
              CMDS+=("--include=$modifiedPath")
              echo "${CMDS[@]}"
            fi
          done
          echo "${CMDS[@]}"

          aws s3 sync database/ s3://${{ secrets.AWS_S3_BUCKET}} --follow-symlinks --exclude "*" "${CMDS[@]}" --exclude "scripts/*" --delete
          aws s3 sync database/ s3://${{ secrets.AWS_S3_BUCKET}} --follow-symlinks --exclude "*" --include=index.json --delete