on: [push]

jobs:
  check_database_updated:
    runs-on: ubuntu-latest 
    name: Test if database was updated in any form
    # Expose step outputs as job outputs
    outputs:
      all_changed_and_modified_files_count: ${{ steps.changed-files.outputs.all_changed_and_modified_files_count }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed and modified files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: database/**
      - name: List all modified files
        env:
          ALL_CHANGED_MODIFIED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_and_modified_files_count }}
        run: |
          echo ${ALL_CHANGED_MODIFIED_FILES_COUNT}
          
  index_database_slides:
    name: Database Slides Indexer
    needs: [check_database_updated]
    if: needs.check_database_updated.outputs.all_changed_and_modified_files_count > 0

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run indexer script
        run: python __indexer.py
      
      - name: Push Index Changes
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add .
          git commit -am "Updating Index Through Github Action"
          git push  -f origin main