on: push

jobs:
  index-slides:
    name: Slide Indexer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run indexer script
        run: py _indexer.py
        shell: sh