on: [push]

jobs:
  check_database_updated:
    runs-on: ubuntu-latest 
    name: Test if database was updated in any form
    # Expose step outputs as job outputs
    outputs:
      all_changed_and_modified_files_count: ${{ steps.changed-files.outputs.all_changed_and_modified_files_count }}
      all_changed_and_modified_files : ${{ steps.changed-files.outputs.all_changed_and_modified_files }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed and modified files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: database/**
      - name: List all modified files
        env:
          ALL_CHANGED_MODIFIED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_and_modified_files_count }}
          ALL_CHANGED_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
        run: |
          for file in ${ALL_CHANGED_MODIFIED_FILES}; do
            echo "$file was changed or modified"
          done
          
  index_slides:
    name: Slides Indexer
    needs: [check_database_updated]
    if: needs.check_database_updated.outputs.all_changed_and_modified_files_count > 0

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run indexer script
        run: python __indexer.py
      
      - name: Push Index Changes
        run: |
          echo "$(git diff --name-only --diff-filter=AM)"
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
  
          if ! git diff --exit-code
          then
            git add .
            git commit -am "Updating Index [GITHUB ACTION]"
            git push  -f origin main
          fi

  s3_database_sync:
    name: Sync Database To S3
    needs: [index_slides]
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Sync with S3
        uses: jakejarvis/s3-sync-action@master
        with:
            args: --follow-symlinks --delete  --exclude "*.py" --exclude "requirements.txt"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'
          SOURCE_DIR: './database'
