on: [push]

jobs:
  check_database_updated:
    runs-on: ubuntu-latest 
    name: Test if database was updated in any form
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed and modified files
        id: check-database-updated
        uses: tj-actions/changed-files@v42
        with:
          files: database/**
      - name: List all modified files
        env:
          ALL_CHANGED_MODIFIED_FILES: ${{ steps.check-database-updated.outputs.all_changed_and_modified_files }}
        run: |
          for file in ${ALL_CHANGED_MODIFIED_FILES}; do
            echo "$file was changed or modified"
          done
          
  index_slides:
    name: Slide Indexer
    runs-on: ubuntu-latest
    needs: [check_database_updated]
    defaults:
      run:
        working-directory: ./database
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make the indexer executable
        run: chmod +x indexer.sh
        
      - name: Run indexer script
        run: ./indexer.sh