on: [push]

jobs:
  slides-modified-check:
    name: Check if slides are modified
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 

      - name: Get modified files in the slides folder
        id: modified-check
        uses: tj-actions/changed-files@v34
        with:
          files: slides/**

      - name: Run step if any slide(s) modified
        if: steps.slides-modified-check.outputs.any_changed == 'true'
        run: echo slides modified

      - name: Prevent from running
        if: steps.slides-modified-check.outputs.any_changed != 'true'
        run: exit 1        

  slides-indexer:
    name: Run indexer script on slides
    runs-on: ubuntu-latest
    needs: [slides-modified-check]
    defaults:
      run:
        working-directory: ./database

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make the indexer executable
        run: chmod +x indexer.sh

      - name: Run indexer script
        run: indexer.sh