on: [push]

jobs:
  index-slides:
    name: Slide Indexer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Make the indexer executable
        run: chmod +x indexer.sh
      - name: Run indexer script
        run: ./indexer.sh